name: Merge PR
description: |
  This action merges a specified pull request.

  ## Usage

  ```yaml
    steps:
      - name: Merge PR
        uses: tmknom/merge-pr-action@v0
        with:
          pull-request: 10
  ```

inputs:
  pull-request:
    required: true
    description: Specifies the pull request to merge as a `number`, `url`, or `branch`.

runs:
  using: composite

  steps:
    - name: Merge
      env:
        PULL_REQUEST: ${{ inputs.pull-request }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -x
        gh pr merge "${PULL_REQUEST}" --merge
      shell: bash
